/**
 * Build script: reads all .gs files from proxy/ and generates a TypeScript
 * module that embeds their contents as string constants.
 *
 * Run via: tsx scripts/bundle-proxy.ts
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const cliRoot = path.resolve(__dirname, '..');
const proxyRoot = path.resolve(cliRoot, '..', 'proxy');
const outFile = path.join(cliRoot, 'src', 'deploy', 'proxy-files.generated.ts');

function readGsFiles(dir: string): Record<string, string> {
  const files: Record<string, string> = {};
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isFile() && entry.name.endsWith('.gs')) {
      files[entry.name] = fs.readFileSync(path.join(dir, entry.name), 'utf-8');
    }
    if (entry.isDirectory()) {
      const subFiles = readGsFiles(path.join(dir, entry.name));
      for (const [name, content] of Object.entries(subFiles)) {
        files[name] = content;
      }
    }
  }
  return files;
}

const gsFiles = readGsFiles(proxyRoot);
const sortedNames = Object.keys(gsFiles).sort();

const lines: string[] = [
  '// Auto-generated by scripts/bundle-proxy.ts — do not edit',
  `// Generated at ${new Date().toISOString()}`,
  '',
  'export const PROXY_FILES: Record<string, string> = {',
];

for (const name of sortedNames) {
  const escaped = gsFiles[name]
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');
  lines.push(`  ${JSON.stringify(name)}: \`${escaped}\`,`);
}

lines.push('};');
lines.push('');

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, lines.join('\n'), 'utf-8');

console.log(`Bundled ${sortedNames.length} proxy files into ${path.relative(cliRoot, outFile)}`);
